-- Update Order_file schema to enable one-to-many relationship instead of one-to-one
DROP TABLE IF EXISTS "Order_file";

CREATE TABLE "Order_file" (
  id bigint generated by default as identity primary key,
  order_id bigint references "Order"(id) on delete cascade,
  "fileName" text
);
